version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: daily_report
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ghcr.io/your-org/daily-report-backend:latest
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:${DB_PASSWORD}@db:5432/daily_report
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  frontend:
    image: ghcr.io/your-org/daily-report-frontend:latest
    environment:
      NODE_ENV: production
      REACT_APP_API_URL: https://reports.your-domain.com/api
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  db-data: